# Generated by Django 5.1.2 on 2024-11-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='last_crawled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
