# Generated by Django 5.1.2 on 2024-11-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newssource_last_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='image_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journalist',
            name='profile_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newspage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
