# Generated by Django 5.1.3 on 2024-11-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_customer_customuser_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='slug',
        ),
    ]
