# Generated by Django 5.1.2 on 2024-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journalist_image_url_journalist_profile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
