# Generated by Django 5.1.2 on 2024-11-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journalist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
