# Generated by Django 5.1.3 on 2024-11-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_digitalprexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_created_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_exported_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_retrieved_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_saved_journalist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_searched',
            field=models.BooleanField(default=False),
        ),
    ]
