# Generated by Django 5.1.3 on 2024-11-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_has_created_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
