# Generated by Django 5.1.3 on 2024-11-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_journalists', models.IntegerField(default=0)),
                ('num_journalists_added_today', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
