# Generated by Django 5.1.3 on 2024-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dbstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
