# Generated by Django 5.1.3 on 2024-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalist_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_access_to_journalists',
            field=models.ManyToManyField(to='core.journalist'),
        ),
    ]
