# Generated by Django 5.1.3 on 2024-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='searches_count',
            field=models.IntegerField(default=0),
        ),
    ]
