# Generated by Django 5.1.3 on 2024-11-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_searches_count'),
        ('djstripe', '0012_2_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='djstripe.customer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='djstripe.subscription'),
        ),
    ]
