# Generated by Django 5.1.3 on 2024-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_product_id_pricingplan_polar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
