# Generated by Django 5.1.3 on 2024-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pricingplan_description_pricingplan_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
