# Generated by Django 5.1.3 on 2024-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_newspage_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
