# Generated by Django 5.1.3 on 2024-11-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_newspage_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
