# Generated by Django 5.1.3 on 2024-11-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_newspage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='x_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
