# Generated by Django 5.1.3 on 2024-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_journalist_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
