# Generated by Django 5.1.3 on 2024-11-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_digitalprexample_confirmed_alter_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
