# Generated by Django 5.1.3 on 2024-11-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_newssource_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='journalists', to='core.newspagecategory'),
        ),
    ]
