# Generated by Django 5.1.3 on 2024-11-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_journalist_categories'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalist',
            index=models.Index(fields=['country'], name='core_journa_country_31cdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalist',
            index=models.Index(fields=['name'], name='core_journa_name_414648_idx'),
        ),
        migrations.AddIndex(
            model_name='journalist',
            index=models.Index(fields=['description'], name='core_journa_descrip_30165d_idx'),
        ),
    ]
