# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_journalist_core_journa_country_31cdeb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sources', to='core.newspagecategory'),
        ),
    ]
