# Generated by Django 5.1.3 on 2024-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fix_embedding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='email_search_with_hunter_tried',
            field=models.BooleanField(default=False),
        ),
    ]
