# Generated by Django 5.1.3 on 2024-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_emaildiscovery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedlist',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='savedlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
