# Generated by Django 5.1.3 on 2024-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_newssource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
