# Generated by Django 5.1.3 on 2024-11-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_journalist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalist',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='embedding',
        ),
    ]
