# Generated by Django 5.1.3 on 2024-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_journalist_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
