# Generated by Django 5.1.3 on 2024-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_dbstat_num_news_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbstat',
            name='num_news_articles',
        ),
        migrations.RemoveField(
            model_name='dbstat',
            name='num_news_articles_added_today',
        ),
        migrations.AddField(
            model_name='newspage',
            name='crawled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
