# Generated by Django 5.1.3 on 2024-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_dbstat_num_news_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbstat',
            name='num_news_articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbstat',
            name='num_news_articles_added_today',
            field=models.IntegerField(default=0),
        ),
    ]
