# Generated by Django 5.1.3 on 2024-12-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
