# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nachopr2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nachopr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_94191b9df3864da48bda2d19a29e6ee0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nachopr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}/nachopr/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nachopr2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d5823c3dfaa44a3bd514b3501297a3d }}
        images: 'nachopr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}/nachopr/webimage:${{ github.sha }}'