# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nachopr2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://nachopr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_94191b9df3864da48bda2d19a29e6ee0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: nachopr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}/nachopr/webimage:${{ github.sha }}
        file: ./Dockerfile
        cache-from: |
          type=registry,ref=nachopr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}/nachopr/webimage:cache
          type=gha,scope=${{ github.ref_name }}-${{ github.workflow }}
        cache-to: |
          type=registry,ref=nachopr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}/nachopr/webimage:cache,mode=max
          type=gha,scope=${{ github.ref_name }}-${{ github.workflow }},mode=max
        platforms: linux/amd64
        provenance: false
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          DOCKER_BUILDKIT=1
        outputs: type=docker,compression-level=3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nachopr2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d5823c3dfaa44a3bd514b3501297a3d }}
        images: 'nachopr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfca508454c2425db52fddd65f8de500 }}/nachopr/webimage:${{ github.sha }}'

# Add concurrency control at the end
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true